# Generated by Django 4.0 on 2022-01-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=180, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=180, verbose_name='Description')),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
