# Generated by Django 4.0 on 2022-01-10 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.birddytor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='posts.birddy'),
        ),
        migrations.AddField(
            model_name='comment',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment'),
        ),
        migrations.AddField(
            model_name='birddy',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author', to='users.birddytor'),
        ),
        migrations.AddField(
            model_name='birddy',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='users.BirddyTor'),
        ),
        migrations.AddField(
            model_name='birddy',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='likes', to='users.BirddyTor'),
        ),
    ]
