# Generated by Django 4.0 on 2022-01-10 00:44

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirddyTor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], max_length=2, verbose_name='user_language')),
                ('user', models.OneToOneField(default=django.contrib.auth.models.AnonymousUser, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
